export default{
employee:[
    {
      id: "EMP001",
      name: "John Smith",
      email: "john.smith@hvacpro.com",
      phone: "+1 (555) 123-4567",
      department: "Installation",
      position: "Senior Technician",
      status: "active",
      joinDate: "2023-01-15",
      location: "Downtown Office",
      performance: 92,
    },
    {
      id: "EMP002",
      name: "Sarah Johnson",
      email: "sarah.johnson@hvacpro.com",
      phone: "+1 (555) 234-5678",
      department: "Maintenance",
      position: "Lead Technician",
      status: "active",
      joinDate: "2022-08-20",
      location: "North Branch",
      performance: 88,
    },
    {
      id: "EMP003",
      name: "Mike Wilson",
      email: "mike.wilson@hvacpro.com",
      phone: "+1 (555) 345-6789",
      department: "Installation",
      position: "Technician",
      status: "active",
      joinDate: "2023-03-10",
      location: "South Branch",
      performance: 85,
    },
    {
      id: "EMP004",
      name: "Emily Davis",
      email: "emily.davis@hvacpro.com",
      phone: "+1 (555) 456-7890",
      department: "Repair",
      position: "Emergency Technician",
      status: "inactive",
      joinDate: "2022-11-05",
      location: "Downtown Office",
      performance: 90,
    },
    {
      id: "EMP005",
      name: "David Brown",
      email: "david.brown@hvacpro.com",
      phone: "+1 (555) 567-8901",
      department: "Maintenance",
      position: "Technician",
      status: "active",
      joinDate: "2023-06-12",
      location: "East Branch",
      performance: 87,
    },
  ],
    departments :["Administration", "Project"],
   positions :{
    Installation: ["Technician", "Senior Technician", "Lead Installer", "Installation Manager"],
    Maintenance: ["Maintenance Technician", "Senior Maintenance Tech", "Maintenance Supervisor"],
    Repair: ["Repair Technician", "Emergency Technician", "Senior Repair Specialist"],
    Sales: ["Sales Representative", "Sales Manager", "Account Executive"],
    Administration: ["Office Manager", "Documentation", "Draftsman", "Account manager", "Purchase department", "Sale deparment"],
    Project:["Sr Engineer", "Engineer", "Trainee engineer", "Project manager", "Supervisor", "Sr Technical", "Technician"]
  },

   locations:["Downtown Office", "North Branch", "South Branch", "East Branch", "West Branch"],

   attendance:{
    history:[
    {
      date: "2024-01-15",
      checkInTime: "8:15 AM",
      checkOutTime: "5:30 PM",
      totalHours: "9h 15m",
      site: "Downtown Office",
      status: "Present",
      overtime: "15m",
    },
    {
      date: "2024-01-14",
      checkInTime: "8:00 AM",
      checkOutTime: "5:00 PM",
      totalHours: "9h 00m",
      site: "Mall Project",
      status: "Present",
      overtime: "0m",
    },
    {
      date: "2024-01-13",
      checkInTime: "8:30 AM",
      checkOutTime: "5:15 PM",
      totalHours: "8h 45m",
      site: "Office Building",
      status: "Late",
      overtime: "0m",
    },
    {
      date: "2024-01-12",
      checkInTime: "8:10 AM",
      checkOutTime: "5:25 PM",
      totalHours: "9h 15m",
      site: "Residential Complex",
      status: "Present",
      overtime: "10m",
    },
    {
      date: "2024-01-11",
      checkInTime: "-",
      checkOutTime: "-",
      totalHours: "0h 00m",
      site: "-",
      status: "Absent",
      overtime: "0m",
    },
  ]
   },

   adminDashboard:{
    recentActivity:[
        {
            employee: "John Smith",
            action: "Checked in",
            location: "Downtown Office",
            time: "8:30 AM",
            status: "on-time",
        },
        {
            employee: "Sarah Johnson",
            action: "Checked out",
            location: "Residential Site A",
            time: "5:15 PM",
            status: "completed",
        },
        {
            employee: "Mike Wilson",
            action: "Late check-in",
            location: "Commercial Site B",
            time: "9:45 AM",
            status: "late",
        },
        {
            employee: "Emily Davis",
            action: "Break started",
            location: "Industrial Site C",
            time: "12:00 PM",
            status: "break",
        },
    ]
   },
   leaveType:["SICK", "CASUAL", "ANNUAL", "UNPAID", "OTHER"]
}