export default{
employee:[
    {
      id: "EMP001",
      name: "John Smith",
      email: "john.smith@hvacpro.com",
      phone: "+1 (555) 123-4567",
      department: "Installation",
      position: "Senior Technician",
      status: "active",
      joinDate: "2023-01-15",
      location: "Downtown Office",
      performance: 92,
    },
    {
      id: "EMP002",
      name: "Sarah Johnson",
      email: "sarah.johnson@hvacpro.com",
      phone: "+1 (555) 234-5678",
      department: "Maintenance",
      position: "Lead Technician",
      status: "active",
      joinDate: "2022-08-20",
      location: "North Branch",
      performance: 88,
    },
    {
      id: "EMP003",
      name: "Mike Wilson",
      email: "mike.wilson@hvacpro.com",
      phone: "+1 (555) 345-6789",
      department: "Installation",
      position: "Technician",
      status: "active",
      joinDate: "2023-03-10",
      location: "South Branch",
      performance: 85,
    },
    {
      id: "EMP004",
      name: "Emily Davis",
      email: "emily.davis@hvacpro.com",
      phone: "+1 (555) 456-7890",
      department: "Repair",
      position: "Emergency Technician",
      status: "inactive",
      joinDate: "2022-11-05",
      location: "Downtown Office",
      performance: 90,
    },
    {
      id: "EMP005",
      name: "David Brown",
      email: "david.brown@hvacpro.com",
      phone: "+1 (555) 567-8901",
      department: "Maintenance",
      position: "Technician",
      status: "active",
      joinDate: "2023-06-12",
      location: "East Branch",
      performance: 87,
    },
  ],
    departments :["Installation", "Maintenance", "Repair", "Sales", "Administration"],
   positions :{
    Installation: ["Technician", "Senior Technician", "Lead Installer", "Installation Manager"],
    Maintenance: ["Maintenance Technician", "Senior Maintenance Tech", "Maintenance Supervisor"],
    Repair: ["Repair Technician", "Emergency Technician", "Senior Repair Specialist"],
    Sales: ["Sales Representative", "Sales Manager", "Account Executive"],
    Administration: ["Office Manager", "HR Coordinator", "Administrative Assistant"],
  },

   locations:["Downtown Office", "North Branch", "South Branch", "East Branch", "West Branch"]

}